2325 extra tables and udef
SuperOffice/SDK-Doc pull request #13
Opened 2020-08-31 07:08 UTC by digitaldiina

2020-08-31 09:31 UTC, AnthonyYates requested changes
Nice addition! Please revise 3rd Party to Third-party.

2020-08-31 09:31 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/advanced/custom-database/custom-database.md
> +* SuperOffice Expander Services license (which you already have for CRMScripts)
Let's not make any assumptions they already have a license. Just label it as a requirement.

2020-08-31 09:31 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/advanced/custom-database/extra-fields.md
> +Unlike user-defined fields, extra fields are added as actual fields to the database tables. There are no pre-defined slots you need to take into consideration, and essentially no limitations.
The actual limitation is dependent on the database table limitations, which in our case in online (using SQL Server) is 1024. Tables that include sparse column sets include up to 30,000 columns, but we do not use these.  The general consensus though is that a large number of columns is a red flag that your table is not properly normalized.

2020-08-31 09:31 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/advanced/custom-database/extra-tables.md
> +SuperOffice Expander Services gives you the the possibility to [create extra tables](./extra-tables.md) in the database. Instantly, these 3rd party tables will be available for standard CRUD operatio
SuperOffice Expander Services **License**...

2020-08-31 09:31 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/advanced/custom-database/udef.md
> +Indexing is good for user experience and performance. The 1st 4 fields of each data type are reserved for indexes.
With regards to ordinals, unless there are a lot, please spell it out as first, second, third....

2020-08-31 09:31 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/advanced/custom-database/udef.md
> +column offset = column ID % (table ID * 256)
This is only true for legacy tables. All new tables in the database (since version 8) are not guaranteed to line up with this logic. Probably best to remove it altogether.

2020-08-31 11:16 UTC, digitaldiina commented on Customer.Service.Support/CRMScript/advanced/custom-database/custom-database.md
> +With some configuration, you can also [add extra fields to the **Details** tab](https://community.superoffice.com/en/search/#/faq/113644).
Added new section at the end of extra fields page.

2020-08-31 11:17 UTC, digitaldiina commented on Customer.Service.Support/CRMScript/advanced/custom-database/udef.md
> +column offset = column ID % (table ID * 256)
removed

2020-08-31 11:22 UTC, digitaldiina commented on Customer.Service.Support/CRMScript/advanced/custom-database/extra-tables.md
> +## Creating an extra table
I think it belongs here for completeness. The previous CS docs had several pages with this, including many screen captures.

2020-08-31 11:24 UTC, digitaldiina commented on Customer.Service.Support/CRMScript/advanced/custom-database/udef.md
> +Indexing is good for user experience and performance. The 1st 4 fields of each data type are reserved for indexes.
The style guide says to not spell it out unless it starts a sentence.

2020-08-31 12:40 UTC, SuperOfficeDevNet commented on Customer.Service.Support/CRMScript/advanced/custom-database/extra-tables.md
> +## Creating an extra table
Agreed, it should remain here... However, since the admin help contains more information  it would be a good idea to ADD a reference to the admin help docs.

2020-08-31 12:58 UTC, SuperOfficeDevNet commented on Customer.Service.Support/CRMScript/advanced/custom-database/udef.md
> +Indexing is good for user experience and performance. The 1st 4 fields of each data type are reserved for indexes.
The style guide does not distinguish between ordinal versus cardinal, and is grammatically wrong. 
Ordinal numbers indicate position or order in relation to other numbers. 
Cardinal numbers, on the other hand, express a quantity of something.

In this context, 1st doesn't not refer to a position in relation to other numbers. If rewritten as "The 1st 2nd 3rd and 4th fields of each datatype, ..." then it would be grammatically correct.

The use of **1st** in this context is cardinal, and therefore should be written as "first".

2020-09-01 07:43 UTC, digitaldiina commented on Customer.Service.Support/CRMScript/advanced/custom-database/extra-fields.md
> +Unlike user-defined fields, extra fields are added as actual fields to the database tables. There are no pre-defined slots you need to take into consideration, and essentially no limitations.
Michel said "no limit". I lean towards sticking to that rather than putting down 1024, because giving a high number might be more encouraging to fill it rather than not quantifying it.

2020-09-01 07:46 UTC, digitaldiina commented on Customer.Service.Support/CRMScript/advanced/custom-database/extra-tables.md
> +## Creating an extra table
added link

2020-09-01 07:47 UTC, digitaldiina commented on Customer.Service.Support/CRMScript/advanced/custom-database/udef.md
> +Indexing is good for user experience and performance. The 1st 4 fields of each data type are reserved for indexes.
fixed all occurrences of 1st and 3rd

2020-09-01 07:56 UTC, SuperOfficeDevNet approved these changes

2020-09-01 07:57 UTC, merged