2569 datatype generic
SuperOffice/SDK-Doc pull request #14
Opened 2020-09-01 08:21 UTC by digitaldiina

Created 1 new file in the datatypes section based on [Michel's blog post](https://community.superoffice.com/en/blog/introduction-to-crmscript-generic/)
Moved API reference files from global functions to a new Generic folder in classes.

2020-09-01 09:30 UTC, AnthonyYates requested changes
Please take a look at my comments and modify or accept the code example suggestions.

2020-09-01 09:30 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/datatypes/generic-type.md
> +}
This code does not run...
```suggestion
if (getTypeName(g) == "DateTime") {
  DateTime dt = GenericToDateTime(g);
}

```

2020-09-01 09:30 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/datatypes/generic-type.md
> +printLine(getTypeDimensions(i));
This line of code does not run.
```suggestion
printLine(getTypeDimensions(i).toString());

```

2020-09-01 09:30 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/datatypes/generic-type.md
> +String[] members = getStructMembers(p);
This code does not run.
```suggestion
String[] members = getStructMembers(getTypeName(p));

```

2020-09-01 09:30 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/datatypes/generic-type.md
> +Generic g = getGenericValue(person, "age");
```suggestion
Generic g = getGenericValue(p, "age");

```

2020-09-01 09:30 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/datatypes/generic-type.md
> +Generic g = convertGenericToString(age);
```suggestion
String g = convertGenericToString(age);

```

2020-09-01 12:36 UTC, digitaldiina commented on Customer.Service.Support/CRMScript/datatypes/generic-type.md
> +Generic g = convertGenericToString(age);
String s

2020-09-01 12:38 UTC, digitaldiina commented on Customer.Service.Support/CRMScript/datatypes/generic-type.md
> +String[] members = getStructMembers(p);
getStructMembers takes the name of the struct, so p should be correct here

2020-09-01 12:41 UTC, digitaldiina commented on Customer.Service.Support/CRMScript/datatypes/generic-type.md
> +printLine(g);
missing semicolon at the end of the revised line

2020-09-02 09:01 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/datatypes/generic-type.md
> +Generic g = convertGenericToString(age);
This does not seem to be changed. Please fix this and request a new review.

2020-09-02 09:02 UTC, AnthonyYates commented on Customer.Service.Support/CRMScript/datatypes/generic-type.md
> +String[] members = getStructMembers(p);
This does not seem to be fixed. Please accept my suggestion, or change to:
String[] members = getStructMembers("Person");

2020-09-02 09:02 UTC, AnthonyYates requested changes
Still needs a couple code fixes.

2020-09-02 09:15 UTC, AnthonyYates approved these changes
Good to go.

2020-09-02 09:16 UTC, merged